import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvder from './-components/AuthProvider'
import Navbar from './-components/navbar'; // Adjust the import to match your file naming convention

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvder>
 <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
    </AuthProvder>
   
  );
}
